# Rule for building a .o file from a .cpp source file -------
.SUFFIXES: .cpp
.cpp.o:
	c++ -c $(CXXFLAGS) $<

# Compile with debug option and all warnings on. ------------
CXXFLAGS = -g -Wall 

# Object modules comprising this application ----------------
OBJ = main.o game.o board.o sstore.o rstrings.o words_d.o tools.o

game: $(OBJ)
	c++  -o game $(CXXFLAGS) $(OBJ)

# Delete .o and exe files and force recompilation. ----------
clean:
	rm -f $(OBJ) game

# Use tools source file from grandparent directory ----------
tools.o:   tools.cpp tools.hpp
	c++ -c $(CXXFLAGS) tools.cpp -o tools.o

# Dependencies ----------------------------------------------
main.o:     main.cpp game.hpp  board.hpp flexT.hpp 
game.o:     game.cpp game.hpp board.hpp rstrings.hpp sstore.hpp flexT.hpp 
board.o:    board.cpp board.hpp words_d.hpp  
words_d.o:  words_d.cpp words_d.hpp words.hpp tools.hpp
rstrings.o: rstrings.cpp rstrings.hpp sstore.hpp flexT.hpp
sstore.o:   sstore.cpp sstore.hpp tools.hpp
